server:
  port: 8080
  servlet:
    context-path: /admin

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecomdb
    username: root
    password: password

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
