INSERT INTO currencies (name, symbol, code) VALUES
('United States Dollar', '$', 'USD'),
('Euro', '€', 'EUR'),
('British Pound Sterling', '£', 'GBP'),
('Japanese Yen', '¥', 'JPY'),
('Australian Dollar', 'AUD', 'AUD'),
('Canadian Dollar', 'CAD', 'CAD'),
('Swiss Franc', 'CHF', 'CHF'),
('Chinese Yuan', '¥', 'CNY'),
('Indian Rupee', '₹', 'INR'),
('Brazilian Real', 'R$', 'BRL'),
('South African Rand', 'R', 'ZAR'),
('Mexican Peso', 'MX$', 'MXN'),
('Singapore Dollar', 'S$', 'SGD'),
('Hong Kong Dollar', 'HK$', 'HKD'),
('New Zealand Dollar', 'NZ$', 'NZD'),
('Russian Ruble', '₽', 'RUB'),
('South Korean Won', '₩', 'KRW'),
('Turkish Lira', '₺', 'TRY'),
('Saudi Riyal', 'ر.س', 'SAR'),
('Argentine Peso', '$', 'ARS'),
('Chilean Peso', '$', 'CLP'),
('Colombian Peso', '$', 'COP'),
('Peruvian Sol', 'S/', 'PEN'),
('Polish Zloty', 'zł', 'PLN'),
('UAE Dirham', 'د.إ', 'AED'),
('Egyptian Pound', 'ج.م', 'EGP'),
('Honduran Lempira', 'L', 'HNL'),
('Icelandic Króna', 'kr', 'ISK'),
('Jordanian Dinar', 'د.أ', 'JOD'),
('Kuwaiti Dinar', 'د.ك', 'KWD'),
('Lebanese Pound', 'ل.ل', 'LBP'),
('Macedonian Denar', 'ден', 'MKD'),
('Malaysian Ringgit', 'RM', 'MYR'),
('Moroccan Dirham', 'د.م.', 'MAD'),
('Omani Rial', 'ر.ع.', 'OMR'),
('Qatari Riyal', 'ر.ق', 'QAR'),
('Serbian Dinar', 'дин.', 'RSD'),
('Sri Lankan Rupee', 'Rs', 'LKR'),
('Tunisian Dinar', 'د.ت', 'TND'),
('Vietnamese Dong', '₫', 'VND'),
('Yemeni Rial', 'ر.ي', 'YER'),
('Bahamian Dollar', '$', 'BSD'),
('Barbadian Dollar', '$', 'BBD'),
('Belize Dollar', '$', 'BZD'),
('Brunei Dollar', '$', 'BND'),
('Cayman Islands Dollar', '$', 'KYD'),
('East Caribbean Dollar', '$', 'XCD'),
('Fijian Dollar', '$', 'FJD'),
('Gambian Dalasi', 'D', 'GMD'),
('Guatemalan Quetzal', 'Q', 'GTQ'),
('Jamaican Dollar', '$', 'JMD'),
('Kenyan Shilling', 'KSh', 'KES'),
('Kyrgyzstani Som', 'сом', 'KGS'),
('Laotian Kip', '₭', 'LAK'),
('Liberian Dollar', '$', 'LRD'),
('Mongolian Tugrik', '₮', 'MNT'),
('Nepalese Rupee', 'Rs', 'NPR'),
('Nigerian Naira', '₦', 'NGN'),
('Pakistani Rupee', '₨', 'PKR'),
('Papua New Guinean Kina', 'K', 'PGK'),
('Paraguayan Guarani', '₲', 'PYG'),
('Rwandan Franc', 'FRw', 'RWF'),
('Sierra Leonean Leone', 'Le', 'SLL'),
('Solomon Islands Dollar', '$', 'SBD'),
('Somali Shilling', 'Sh', 'SOS'),
('Surinamese Dollar', '$', 'SRD'),
('Tanzanian Shilling', 'TSh', 'TZS'),
('Tongan Paʻanga', 'T$', 'TOP'),
('Trinidad and Tobago Dollar', '$', 'TTD');
