server:
  port: 8000
  servlet:
    context-path: /site
  shutdown: graceful

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecomdb
    username: root
    password: password

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/mysql

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

payment:
  vnpay:
    tmn: ${VNPAY_TMN_CODE:N/a}
    secret: ${VNPAY_SECRET:N/a}
    url: ${VNPAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
    return-url: ${VNPAY_RETURN_URL:http://localhost:8000/site/payment/vnpay/callback}

logging:
  level:
    root: warn
    com.tranhuy105: debug