server:
  port: 80
  servlet:
    context-path: /site

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecomdb
    username: root
    password: password

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/mysql

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

payment:
  vnpay:
    tmn: ${VNPAY_TMN_CODE}
    secret: ${VNPAY_SECRET}

logging:
  level:
    root: warn
    com.tranhuy105: debug