server:
  port: 8080
  servlet:
    context-path: /admin

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecomdb
    username: root
    password: password

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/mysql

logging:
  level:
    root: warn
    com.tranhuy105: debug

ghn:
  api:
    token: ${GHN_TOKEN}
    shopId: ${GHN_SHOP_ID}
    url: https://dev-online-gateway.ghn.vn/shiip/public-api/v2